config/routes.rb
Slug2::Application.routes.draw do
  resources :items
  resources :categories
  resources :pages
  
  match "*path", :to => "categories#display", :as => :display

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :item
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :content, :parent_id, :title
  acts_as_nested_set
  
  has_many :categorizations
  has_many :items, through: :categorizations
  
  extend FriendlyId
  friendly_id :title, :use => :scoped, :scope => :parent

  before_save :compute_path
  def compute_path
    node, nodes = self, []
    nodes << node = node.parent while node.parent

    self.path = nodes.reverse.push(self).collect(&:slug).join("/")
  end
  
  def get_all_related_items
      items = []
      self.children.each do |category|
         items << category.items
      end
      items
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :price, :title, :category_ids
  has_many :categorizations
  has_many :categories, through: :categorizations
  
  extend FriendlyId
   friendly_id :title, :use => :slugged
  end

app/models/item_cateogry.rb
class ItemCateogry < ActiveRecord::Base
  belongs_to :item  
  belongs_to :category
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :parent_id, :title
   acts_as_nested_set
    
    extend FriendlyId
     friendly_id :title, :use => :scoped, :scope => :parent

     before_save :compute_path
     def compute_path
       node, nodes = self, []
       nodes << node = node.parent while node.parent
       
       self.path = nodes.reverse.push(self).collect(&:slug).join("/")
     end
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /pages/1
   # GET /pages/1.json
   def display
     @category = Category.find_by_path(params[:path])
     @items = @category.items.paginate :page => params[:page], :per_page => 2
     @itemas = @category.get_all_related_items
         
     respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @page }
     end
   end
   
  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end
  
  # GET /pages/1
  # GET /pages/1.json
  def display
    @page = Page.find_by_path(params[:path])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end
  
  

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorizations_helper.rb
module CategorizationsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
	<%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.title}" }, { :include_blank => '-- None --' } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/display.html.erb
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<p id="notice"><%= notice %></p>

<p><% @category.self_and_ancestors.each do |x| %>
	<%= link_to x.title, display_url(x.path) %> >
<% end %></p>

<p><% @category.children.each do |x| %>
	<%= link_to x.title, display_url(x.path) %> | 
<% end %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Content:</b>
  <%= @category.content %>
</p>

<p>
  <b>Parent:</b>
  <%= @category.parent_id %>
</p>

<b>Itemas:</b>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.title, item %></li>
  <% end %>
</ul>

<%= debug @itemas %>


<%= will_paginate @items  %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <!-- <th>Content</th> -->
    <!-- <th>Parent</th> -->
    <!-- <th>Path</th> -->
    <!-- <th>Slug</th> -->
    <th>Action</th>
  
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td>
<%= "#{'-' * category.level}" %>   
<%= link_to  "#{category.title}", display_url(category.path)  %>
 	<!-- <td><%= category.content %></td> -->
    <!-- <td><%= category.parent_id %></td> -->
    <!-- <td><%= category.path %></td> -->
    <!-- <td><%= category.slug %></td> -->
    <td><%= link_to 'Show', category %>
    <%= link_to 'Edit', edit_category_path(category) %>
    <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Content:</b>
  <%= @category.content %>
</p>

<p>
  <b>Parent:</b>
  <%= @category.parent_id %>
</p>

<p>
  <b>Path:</b>
  <%= @category.path %>
</p>

<p>
  <b>Slug:</b>
  <%= @category.slug %>
</p>

<b>Itemas:</b>
<ul>
  <% @category.items.each do |item| %>
    <li><%= link_to item.title, item %></li>
  <% end %>
</ul>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
<% if @item.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

	<ul>
		<% @item.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :title %><br />
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :description %><br />
	<%= f.text_area :description, :class => "tinymce" %>
</div>
<div class="field">
	<%= f.label :price %><br />
	<%= f.text_field :price %>
</div>

<div class="field">
	<%= hidden_field_tag "product[category_ids][]", nil %>
	<% Category.all.each do |category| %>
	<%= check_box_tag "item[category_ids][]", category.id, @item.category_ids.include?(category.id), id: dom_id(category) %>
	<%= label_tag dom_id(category), "#{'-' * category.level} #{category.title}"  %><br>
	<% end %>
</div>
<%# nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.title}" } %>
<% #f.select :category_ids, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.title}" }, { :include_blank => '-- None --' }, :multiple => true %>

<div class="actions">
	<%= f.submit %>
</div>
<%= tinymce%>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.title %></td>
    <td><%= item.description %></td>
    <td><%= item.price %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Title:</b>
  <%= @item.title %>
</p>

<p>
  <b>Description:</b>
  <%= simple_format @item.description %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<b>Categories:</b>
<ul>
  <% @item.categories.each do |category| %>
    <li><%= link_to category.title, display_url(category.path) %></li>
  <% end %>
</ul>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Slug2" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Slug2</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Items", items_path  %></li>
              <li><%= link_to "Categories", categories_path  %></li>
              <li><%= link_to "Pages", pages_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
	<% #f.select(:parent_id, Page.all.collect { |p| [p.title, p.id] }, { :include_blank => 'None' }) %>
	<%= f.select :parent_id, nested_set_options(Page, @page) {|i| "#{'-' * i.level} #{i.title}" }, { :include_blank => '-- None --' } %>
	

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_submenu_pages.html.erb
<ul>
  <% pages.each do |page, children| %>
    <li>
      <%= link_to_unless_current page.title, display_url(page.path) %>
      <%= render 'submenu_pages', pages: children if children.present? %>
    </li>
  <% end %>
</ul>

app/views/pages/display.html.erb
<p id="notice"><%= notice %></p>

<div class="menu">
	<ul id="menu">
	  <% Page.roots.each do |page| %>
	    <li><%= link_to page.title, display_url(page.path), class: ("active" if @page.root == page) %></li>
	  <% end %>
	</ul>
</div>

<p><% @page.ancestors.each do |x| %>
	<%= link_to x.title, display_url(x.path) %>
<% end %></p>


<div id="submenu">
  <%= render 'submenu_pages', pages: @page.children %>
</div>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>

<p>
  <b>Parent:</b>
  <%= @page.parent_id %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Parent</th>
    <th>Slug</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.content %></td>
    <td><%= page.parent_id %></td>
    <td><%= page.slug %></td>
    <td><%= page.path %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>

<p>
  <b>Parent:</b>
  <%= @page.parent_id %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>